### PR TITLE
Upgrade to qt6 in preparation for OVITO 3.8.0

### PR DESCRIPTION
**Pull request by nnn911**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] ~Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] ~Ensured the license file is being packaged.~

Qt5 support has been removed in version 3.8.0. Therefore, the following changes are proposed: 
- Upgrade from qt5 to qt6
- Remove runtime dependency on boost library (headers only are needed to build OVITO)

Additionally, the ‘about’ section has been updated.

### CODE REVIEW

**Comment by nnn911** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
```
-- Found Git: /opt/conda/bin/git (found version "2.39.2") 
CMake Error at src/3rdparty/qwt/CMakeLists.txt:24 (FIND_PACKAGE):
  By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5" (requested
  version 5.12) with any of the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
```

**Comment by jan-janssen** [comment]
Mac OS X ARM fails with:
```
CMake Error at CMakeLists.txt:69 (FIND_PACKAGE):
  Found package configuration file:

    /Users/runner/miniforge3/conda-bld/ovito_1677881450213/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.


-- Configuring incomplete, errors occurred!
```

Mac OS X on x86_64 finds the wrong python version: 
```
Found Python3: /Library/Frameworks/Python.framework/Versions/Current/bin/python3.11 (found version "3.11.2") found components: Interpreter 
-- 
```
This results in the `sphinx` error: 
```
Found Python3: /Library/Frameworks/Python.framework/Versions/Current/bin/python3.11 (found version "3.11.2") found components: Interpreter 
-- 
```

@stukowski Is it possible to manually point cmake to the correct python version?

**Comment by stukowski** [comment]
> @stukowski Is it possible to manually point cmake to the correct python version?

Yes, in our own recipe we do the following (build.sh & bld.bat):

```
cmake \
    -DPython3_ROOT_DIR="${PREFIX}" \
    -DPython3_FIND_STRATEGY=LOCATION \
    -DPython3_FIND_VIRTUALENV=ONLY \
    -DPython3_EXECUTABLE=${PYTHON} \
   ...
```
```
cmake ^
    -DPython3_ROOT_DIR=%PREFIX% ^
    -DPython3_FIND_STRATEGY=LOCATION ^
    -DPython3_FIND_VIRTUALENV=ONLY ^
    -DPython3_EXECUTABLE=%PYTHON% ^
   ...
```
I'm not sure about the Qt6 related error on osx/arm64. It is preceded by the message
```
CMake Error at /Users/runner/miniforge3/conda-bld/ovito_1677881450213/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/cmake/Qt6/QtPublicDependencyHelpers.cmake:255 (message):
  To use a cross-compiled Qt, please set the QT_HOST_PATH cache variable to
  the location of your host Qt installation.
```
which suggests that it is related to cross-compilation. We don't do cross-compilation in our own recipe, so I haven't encountered this kind of issue before. We should check what other conda-forge recipes do to build against Qt6 successfully.

**Comment by jan-janssen** [comment]
```
 To use a cross-compiled Qt, please set the QT_HOST_PATH cache variable to
  the location of your host Qt installation.
```

**Comment by jan-janssen** [comment]
While the cross compiling looks more promising the Mac Os X build still fails
```
[ 31%] Linking CXX shared library ../../../lib/ovito/libovito_qwt.dylib
ld: framework not found Metal
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/3rdparty/qwt/CMakeFiles/Qwt.dir/build.make:1607: lib/ovito/libovito_qwt.dylib] Error 1
make[1]: *** [CMakeFiles/Makefile2:879: src/3rdparty/qwt/CMakeFiles/Qwt.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by jan-janssen** [comment]
> While the cross compiling looks more promising the Mac Os X build still fails
> 
> ```
> [ 31%] Linking CXX shared library ../../../lib/ovito/libovito_qwt.dylib
> ld: framework not found Metal
> clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [src/3rdparty/qwt/CMakeFiles/Qwt.dir/build.make:1607: lib/ovito/libovito_qwt.dylib] Error 1
> make[1]: *** [CMakeFiles/Makefile2:879: src/3rdparty/qwt/CMakeFiles/Qwt.dir/all] Error 2
> make: *** [Makefile:146: all] Error 2
> ```

This issue remains even when removing the cross compiling specific parts. I tested that in https://github.com/conda-forge/ovito-feedstock/pull/77

**Comment by stukowski** [comment]
I don't have a good idea yet what is going on here. Unfortunately, I am not familiar enough with the conda-forge build environments. 
I looked for other feedstocks that consume the `qt6-main` package but could not find one so far - aside from pyside6, which is not a regular application. Is there a way to search the conda-forge channel for packages that have qt6-main as a dependency?

**Comment by hmaarrfk** [comment]
you likely have to either disable metal, or bump the OSX SDK:

https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks

Try to first increase the OSX (features used at compilation time), then the deployment target (what machines can use the final binaries)

See how they can be out of sync at first in qt
https://github.com/conda-forge/qt-main-feedstock/blob/qt6/recipe/conda_build_config.yaml#L4

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by jan-janssen** [comment]
@hmaarrfk  Thanks a lot

**Comment by hmaarrfk** [comment]
Yeah. It's easy to forget to rerender

**Pull request merged**
